apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ruub4dxo8-python 
  janus-idp.io/tekton: ruub4dxo8-python
  backstage.io/kubernetes-id: ruub4dxo8-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ruub4dxo8-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml